<%@ Page Title="" Language="C#" MasterPageFile="~/es/Es_Master.Master" AutoEventWireup="true" CodeBehind="Barnices_Base_Agua.aspx.cs" Inherits="WebSanchez2016.es.Tintas_y_Materiales.Offset_Hoja.BarnicesBaseAgua" %>

<asp:Content ID="Content1" ContentPlaceHolderID="TitleContent" runat="server">
    Barnices base agua - Offset hoja - Tintas y materiales - Grupo S&aacute;nchez
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <div class="TintasyMateriales" id="divTintasyMateriales" runat="server">
    <div class="MantillasDay"> <img class="InfoCatImgHdr" src="../../../Global_Imgs/Contenido/PlecaBarBaseAgua.png" alt="Imagen Barnices Base Agua" title="Mantillas Day"/>
<div class="tablaBarniz">
    <table>
        <tbody>
             <tr>
                <td colspan="13" class="InfoCatEspacio"></td>
            </tr>
           <!-- <tr>  <td colspan="13" class="InfoCatTitHdr">Tintas policrom&iacute;a CS 9</td> </tr>-->


            <!--Mahonry-->
            <tr><td class="InfoCatBlanco"><br></td><td class="InfoCatBlanco"></td><td class="InfoCatBlanco"></td><td class="InfoCatBlanco"></td><td class="InfoCatBlanco"></td><td class="InfoCatBlanco"></td><td class="InfoCatBlanco"></td><td class="InfoCatBlanco"></td><td class="InfoCatBlanco"></td><td class="InfoCatBlanco"></td><td class="InfoCatBlanco"></td><td class="InfoCatBlanco"></td><td class="InfoCatBlanco"></td></tr>
            <tr>
                <td class="bordePunteadoGrisDerecha InfoCatBlanco alineadoAbajo negrita">Descripción</td>
                <td class="bordePunteadoGrisDerecha InfoCatBlanco alineadoAbajo sinPadding " style="text-align: center;">
                    <img class="imagenEncabezado" src="../../../Global_Imgs/Tabla/EncabezadoBarnicesBaseAgua/clave.png" alt="Encabezado Clave" >
                </td>
                <td class="bordePunteadoGrisDerecha InfoCatBlanco alineadoAbajo sinPadding" style="text-align: center;">
                    <img class="imagenEncabezado" src="../../../Global_Imgs/Tabla/EncabezadoBarnicesBaseAgua/viscosidad.png" alt="Encabezado viscosidad" >
                </td>
                <td class="bordePunteadoGrisDerecha InfoCatBlanco alineadoAbajo sinPadding" style="text-align: center;">
                    <img class="imagenEncabezado" src="../../../Global_Imgs/Tabla/EncabezadoBarnicesBaseAgua/Rango.png" alt="Encabezado Rango">
                </td>
                <td class="bordePunteadoGrisDerecha InfoCatBlanco alineadoAbajo sinPadding" style="text-align: center;">
                    <img class="imagenEncabezado" src="../../../Global_Imgs/Tabla/EncabezadoBarnicesBaseAgua/Sustrato.png" alt="Encabezado Sustrato">
                </td>
                <td class="bordePunteadoGrisDerecha InfoCatBlanco alineadoAbajo sinPadding" style="text-align: center;">
                    <img class="imagenEncabezado" src="../../../Global_Imgs/Tabla/EncabezadoBarnicesBaseAgua/Rango.png" alt="Encabezado Rango">
                </td>
                <td class="bordePunteadoGrisDerecha InfoCatBlanco alineadoAbajo sinPadding" style="text-align: center;">
                    <img class="imagenEncabezado" src="../../../Global_Imgs/Tabla/EncabezadoBarnicesBaseAgua/TorreBarniz.png" alt="Encabezado Torre Barniz">
                </td>
                <td class="bordePunteadoGrisDerecha InfoCatBlanco alineadoAbajo sinPadding" style="text-align: center;">
                    <img class="imagenEncabezado" src="../../../Global_Imgs/Tabla/EncabezadoBarnicesBaseAgua/Tintero.png" alt="Encabezado Tintero">
                </td>
                <td class="bordePunteadoGrisDerecha InfoCatBlanco alineadoAbajo sinPadding" style="text-align: center;">
                    <img class="imagenEncabezado" src="../../../Global_Imgs/Tabla/EncabezadoBarnicesBaseAgua/SistHumectado.png" alt="Encabezado Sistema Humectado">
                </td>
                <td class="bordePunteadoGrisDerecha InfoCatBlanco alineadoAbajo sinPadding" style="text-align: center;">
                    <img class="imagenEncabezado" src="../../../Global_Imgs/Tabla/EncabezadoBarnicesBaseAgua/EtiqImpPublic.png" alt="Encabezado Etiquetas e impresos Publicitarios">
                </td>
                <td class="bordePunteadoGrisDerecha InfoCatBlanco alineadoAbajo sinPadding" style="text-align: center;">
                    <img class="imagenEncabezado" src="../../../Global_Imgs/Tabla/EncabezadoBarnicesBaseAgua/EmpaqPlegad.png" alt="Encabezado Empaques plegadizo">
                </td>
                <td class="bordePunteadoGrisDerecha InfoCatBlanco alineadoAbajo sinPadding" style="text-align: center;">
                     <img class="imagenEncabezado" src="../../../Global_Imgs/Tabla/EncabezadoBarnicesBaseAgua/EmpaqPlegadRev.png" alt="Encabezado empaque plegadizo Reverso">
                </td>

                <td class="InfoCatBlanco alineadoAbajo sinPadding" style="text-align: center;">
                    <img  class="imagenEncabezado" src="../../../Global_Imgs/Tabla/EncabezadoBarnicesBaseAgua/EtiqMetaliz.png" alt="Encabezado Metalizado">

                </td></tr>
            <!--<tr><td class="InfoCatTitHdr bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="InfoCatTitHdr bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="InfoCatTitHdr bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="InfoCatTitHdr bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="InfoCatTitHdr bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="InfoCatTitHdr bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="InfoCatTitHdr bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="InfoCatTitHdr bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="InfoCatTitHdr bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="InfoCatTitHdr bordePunteadoGrisDerecha InfoCatBlanco "></td><td class="InfoCatTitHdr bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="InfoCatTitHdr bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="InfoCatTitHdr InfoCatBlanco"></td></tr>-->
            <tr><td colspan="13" class="InfoCatTitHdr InfoCatBlanco"></td></tr>
            <tr><td class="bordePunteadoGrisDerecha InfoCatBlanco">Barniz brillante 20V AQ</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">AQ 313</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">20</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">18-22</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">Cart&oacute;n y couché</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">Frente y vuelta</td><td class="bordePunteadoGrisDerecha InfoCatBlanco sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="bordePunteadoGrisDerecha InfoCatBlanco sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatBlanco sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="InfoCatBlanco"></td></tr>
            <tr><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">Barniz rápido secado AQ</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">AQ 674</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">18</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">16-20</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">Cart&oacute;n y couché</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">Frente y vuelta</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz"></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz"></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz"></td><td class="InfoCatColorTablaBarniz"></td></tr>
            <tr><td class="bordePunteadoGrisDerecha InfoCatBlanco">Barniz ultra brillante 30V AQ</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">AQ 670</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">30</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">26-30</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">Cart&oacute;n</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">Frente</td><td class="bordePunteadoGrisDerecha InfoCatBlanco sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="bordePunteadoGrisDerecha InfoCatBlanco sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="InfoCatBlanco"></td></tr>
            <tr><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">Barniz primer para UV AQ</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">AQ 669</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">20</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">18-22</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">Cart&oacute;n y couché</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">Frente</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz"></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz"></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz"></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz"></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz"></td><td class="InfoCatColorTablaBarniz"></td></tr>
            <tr><td class="bordePunteadoGrisDerecha InfoCatBlanco">Barniz brillante batería AQ</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">AQ 540</td><td class="bordePunteadoGrisDerecha InfoCatBlanco"><span title="(1) Viscosidad en Brookfield RVT: aguja #3; 10 RPM; 23ºC.">3500 cps (1)</span></td><td class="bordePunteadoGrisDerecha InfoCatBlanco">
                4900-5100</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">Cart&oacute;n</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">Frente</td><td class="bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="bordePunteadoGrisDerecha InfoCatBlanco sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="bordePunteadoGrisDerecha InfoCatBlanco sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="InfoCatBlanco"></td></tr>
            <tr><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">Barniz mate 20V AQ</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">AQ 522</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">20</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">18-22</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">Cart&oacute;n y couché</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">Frente y vuelta</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz"></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz"></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz"></td><td class="InfoCatColorTablaBarniz"></td></tr>
            <tr><td class="bordePunteadoGrisDerecha InfoCatBlanco">Barniz mate Batería AQ</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">AQ 563</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">
                <span title="(1) Viscosidad en Brookfield RVT: aguja #3; 10 RPM; 23ºC.">5000 cps (1)</span></td><td class="bordePunteadoGrisDerecha InfoCatBlanco">3000-3500</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">Cart&oacute;n</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">Frente</td><td class="bordePunteadoGrisDerecha InfoCatBlanco sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatBlanco sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="bordePunteadoGrisDerecha InfoCatBlanco sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="InfoCatBlanco"></td></tr>
            <tr><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">Barniz brillante AQ</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">AQ 579</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">20</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">18-22</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">Cart&oacute;n</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">Frente</td><td class="bordePunteadoGrisDerecha  InfoCatColorTablaBarniz sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz"></td><td class="bordePunteadoGrisDerecha  InfoCatColorTablaBarniz sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz"></td><td class="InfoCatColorTablaBarniz"></td></tr>
            <tr><td class="bordePunteadoGrisDerecha InfoCatBlanco">Barniz brillante antigrasa 20V AQ</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">AQ 141</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">20</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">18 - 22</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">Cart&oacute;n</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">Frente</td><td class="bordePunteadoGrisDerecha InfoCatBlanco sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="bordePunteadoGrisDerecha InfoCatBlanco sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatBlanco sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="InfoCatBlanco"></td></tr>
            <tr><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">Barniz release AQ</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">AQ 672</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">14</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">12-14</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">Cart&oacute;n</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">Frente</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz "><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz"></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz"></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz"></td><td class="bordePunteadoGrisDerecha  InfoCatColorTablaBarniz sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz"></td><td class="InfoCatColorTablaBarniz"></td></tr>
            <tr><td class="bordePunteadoGrisDerecha InfoCatBlanco">Barniz Termorresistente AQ</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">AQ 513</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">20</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">18-22</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">Cart&oacute;n</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">Frente</td><td class="bordePunteadoGrisDerecha InfoCatBlanco sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="bordePunteadoGrisDerecha InfoCatBlanco sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="bordePunteadoGrisDerecha InfoCatBlanco sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="InfoCatBlanco"></td></tr>
            <tr><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">Barniz brillante licores AQ</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">AQ 159</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">22</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">20-24</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">Cart&oacute;n</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">Frente</td><td class="bordePunteadoGrisDerecha  InfoCatColorTablaBarniz sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz"></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz"></td><td class="bordePunteadoGrisDerecha  InfoCatColorTablaBarniz sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha  InfoCatColorTablaBarniz sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz"></td><td class="InfoCatColorTablaBarniz"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td></tr>
            <tr><td class="bordePunteadoGrisDerecha InfoCatBlanco">Barniz Blister AQ</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">AQ 600</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">
                35</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">35-40</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">Cart&oacute;n</td><td class="bordePunteadoGrisDerecha InfoCatBlanco">Frente</td><td class="bordePunteadoGrisDerecha InfoCatBlanco sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="bordePunteadoGrisDerecha InfoCatBlanco sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatBlanco"></td><td class="InfoCatBlanco"></td></tr>
            <tr><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">Barniz Tacto Suave AQ</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">AQ 617</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">40</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">38-42</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">Cart&oacute;n</td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">Frente</td><td class="bordePunteadoGrisDerecha  InfoCatColorTablaBarniz sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz"></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz"></td><td class="bordePunteadoGrisDerecha  InfoCatColorTablaBarniz sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha  InfoCatColorTablaBarniz sinPadding"><div class="img-centrado"><img alt="imagen bullet" width="10" height="11"  src="../../../Global_Imgs/Tabla/varios/vineta.png"></div></td><td class="bordePunteadoGrisDerecha InfoCatColorTablaBarniz">
                &nbsp;</td><td class="InfoCatColorTablaBarniz"></td></tr>

            <tr>
                <td colspan="13" class="InfoCatBlanco"><br>(1) Viscosidad en Brookfield RVT: aguja #3; 10 RPM; 23ºC.</td>
            </tr>
            <!--end mahonry-->
            <tr>
                <td colspan="13" class="InfoCatEspacio"></td>
            </tr>
            <tr>
                <td colspan="3" class="InfoCatTitHdr">Almacenamiento y manejo</td><td colspan="10"></td>
            </tr>
            <tr>
                <td colspan="13" class="InfoCatBlanco">Almacénalos en lugares frescos y con buena ventilación, manteniendo bien cerrados los envases.  Te recomendamos el uso de guantes y lentes cuando los manipules.  En caso de que tengan contacto con tu piel, lávate perfectamente con agua y jabón.												
</td>
            </tr>
            <tr>
                <td colspan="13" class="InfoCatEspacio"></td>
            </tr>
            <tr>
                <td colspan="3" class="InfoCatTitHdr">Regulaciones</td><td colspan="10"></td>
            </tr>

            <tr>
                <td colspan="13" class="InfoCatBlanco">Son amables con el medio ambiente debido a que los producimos con materiales exentos de metales pesados restringidos. Cumplen con la Norma Oficial Mexicana NOM-252-SSA1-2011 de la Secretaría de Salud.  Cumplen con la Regulación de CONEG de USA.  Son adecuados para ser utilizados en empaques para alimentos siempre que exista una barrera funcional, tal y como lo indica el Código Federal de Regulaciones de USA (Título 21, partes 174 a 178), conforme la regulación FDA.  El AQ141 es adecuado para ciertas aplicaciones en las que habrá contacto directo con alimentos.  Debido a las variables que existen en el proceso de impresión es conveniente realices tus propios controles y ensayos de aplicación.  Cualquier duda respecto al uso, aplicación y resistencias de nuestros productos nos puedes consultar a 
				<a href="mailto:aquagloss@sanchez.com.mx">aquagloss@sanchez.com.mx</a></td>

            </tr>

            <tr>

                <td colspan="13" class="InfoCatEspacio"></td>

            </tr>

            <tr>

                <td colspan="13" class="InfoCatImgFooter"><a href="https://www.sanchez.com.mx"> <img src="../../../Global_Imgs/Logo_Sanchez.jpg" alt="S&aacute;nchez S.A. de C.V." title="S&aacute;nchez S.A. de C.V."></a> </td>

            </tr>

        </tbody>
    </table>
</div>
</div>

    </div>
</asp:Content>
